[workspace]
members = ["problem-1", "problem-2", "problem-3", "problem-4", "problem-5", "problem-6", "problem-7"]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false
